name: Docker Image CI

uses: digitalocean/action-doctl@v2
      with:                                                 # This line is crashing?
            token: ${{ secrets.FIRSTBUILDERSECRET }}
        
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
